### ISSUE TITLE
Use DFI

### ISSUE THREAD

**Issue by fieldhof** [bpetri/nativeLoad#11]
Get the newest celix with rsa dfi to work on android.

**Comment by marcojansen** [comment]
Crashing when using DFI, the DFI is still too experimental. Might use it later when it has stabilized

**Comment by bpetri** [comment]
There has been some bugfixes since the last version. Could you re-test RSA_DFI and try to isolate the bugs you see.

**Comment by marcojansen** [comment]
There are still some bugs, when shutting down and on the galaxy s3 mini it still crashes sometimes. When shutting down i got the following error: 
0x9eb96a9c in logHelper_log (loghelper=0x0, level=OSGI_LOGSERVICE_INFO, 
    message=0x9ebd6e90 "RSA_DFI: Removing imported service")
    at celix/log_service/public/src/log_helper.c:185
185     if (!logged && loghelper->stdOutFallback) {

(gdb) bt
 0x9eb96a9c in logHelper_log (loghelper=0x0, level=OSGI_LOGSERVICE_INFO, 
    message=0x9ebd6e90 "RSA_DFI: Removing imported service")
    at celix/log_service/public/src/log_helper.c:185
0x9eb7fe24 in remoteServiceAdmin_removeImportedService (admin=0xaec28ab0, registration=0xaecbf560)
    at celix/remote_services/remote_service_admin_dfi/rsa/

**Comment by marcojansen** [comment]
Everything works fine until the moment you kill/stop something . Once a device goes down with an error or application gets closed, the queue will follow after a few seconds (10-20 seconds). The error with the queue 

00016e6f  /system/lib/libc.so (free+10): Routine mbsnrtowcs at ??:?
 00020cbc  /libdiscovery_etcd.so (etcdWatcher_removeEntry+152): Routine etcdWatcher_removeEntry at celix/remote_services/discovery_etcd/private/src/etcd_watcher.c:234

**Comment by bpetri** [comment]
The last error you see (etcdWatcher_removeEntry) is already fixed in the current celix.

**Comment by marcojansen** [comment]
Seems stable now, still crashed a few times on my galaxy s6 but couldn't find the crashlog. Pushed to the master branch, older implementation with endpoints  is no longer used.
